
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: institutions empower your stundents to succeed academically with QuickTakes
  description: institutions empower your stundents to succeed academically with QuickTakes
  icon: "email"

# Defines the structure of this component, as well as the default values
blueprint:
  title: institutions empower your stundents to succeed academically with QuickTakes
  contentTitle: 
    en: Empower your students to succeed academically with QuickTakes
    zh_hk: 
    fr:
    sp:
  description: 
    en: >-
      Embrace AI in your institution and build an inclusive campus that removes
      barriers to learning and gives all students a path to success.
    zh_hk: 
    fr:
    sp:
  buttonTxt:
    en: Contact Us
    zh_hk: 
    fr: test
    sp:
  image: /never-forget-a-lecture.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    type: textarea
  description.zh_hk:
    type: textarea
  description.fr:
    type: textarea
  description.sp:
    type: textarea

