
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Institutions briefing
  description: Institutions briefing section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Institutions briefing section
  image: /insititutions/briefing.png
  items:
    - title: 
        en: Disability Services Centers
        zh_hk: 
        fr: 
        sp:
      content: 
        en: >-
          We help neurodiverse students thrive by championing their uniqueness
          and supporting them academically.
        zh_hk: 
        fr:
        sp:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items[*].content.en:
    type: textarea
  items[*].content.zh_hk:
    type: textarea
  items[*].content.fr:
    type: textarea
  items[*].content.sp:
    type: textarea
