
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Education Book Mentions Section
  description: Education Book Mentions Section
  icon: "help"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Education Book Mentions Section
  contentTitle: Book Mentions
  list: 
    - image: /bookmentions.png
      title: "Brave New Words: How AI Will Revolutionize Education (and Why That's a Good Thing) Book"
      auth: By Salman Khan
      link: https://bookshop.org/p/books/brave-new-words-how-ai-will-revolutionize-education-and-why-that-s-a-good-thing-salman-khan/20453214?ean=9780593656952

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
