
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Institutions Banner
  description: Institutions Banner section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Institutions Banner section
  contentTitle: 
    en: Revolutionizing Accessibility in the Classroom with AI
    zh_hk: 
    fr: 
    sp:
  subTitle: 
    en: >-
      Ensure students of all abilities and backgrounds can succeed academically
      with QuickTakes AI-generated study aids.
    zh_hk: 
    fr: 
    sp:
  buttonTxt:
    en: Contact Us
    zh_hk: 
    fr: test
    sp:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
