
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home portrail
  description: Home portrail section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home portrail Section
  list:
    - title: Studying Just Got Easier
      image: /study-just-got-easier.png
      description: >-
        <p>Record your lecture and QuickTakes creates <strong>outlines</strong>,
        <strong>study guides</strong>, a <strong>glossary </strong>and more!</p>
    - title: Learn in Different Ways
      image: /learn-in-different-ways.png
      description: >-
        <p>QuickTakes provides <strong>related videos</strong> and practice
        <strong>problems </strong>so you can learn in the way that best suits
        you!</p>
    - title: Personalize Anytime
      image: /questions-answer.png
      description: >-
        <p>Need to add your own notes to a QuickTake? Highlight, edit or add
        text, input images and even create math formulas!</p>

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
