paths:
  uploads: public/uploads
  data: data
collections_config:
  data:
    path: data
    output: false
    filter:
      base:
      include:
      exclude:
    description: ''
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
source_editor:
  tab_size: 2
  show_gutter: false
  them: dawn
