paths:
  uploads: public/uploads
  data: data
collections_config:
  # data:
  #   path: data
  #   output: false
  #   filter:
  #     base:
  #     include:
  #     exclude:
  #   description: ''
  #   icon: notes
  #   _editables: {}
  #   _inputs: {}
  #   _select_data: {}
  #   _structures: {}
  #   disable_add: true
  #   disable_add_folder: true
  #   disable_file_actions: false
  #   schemas: {}
  pages:
    name: Pages
    path: content
    url: '/[slug]'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
_inputs: 
  avatar:
    type: image
  paragraph:
    type: textarea
  question:
    type: textarea
  answer:
    type: html
  portrait_section[*].description:
    type: html
  testimonials_section.list[*].quote:
    type: textarea
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
source_editor:
  tab_size: 2
  show_gutter: true
timezone: Etc/UTC
