paths:
  uploads: public/uploads
  collections: content
  data: data
collections_config:
  data:
    path: data
    output: false
    filter:
      base:
      include:
      exclude:
    description: ''
    icon: notes
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: true
    disable_add_folder: true
    disable_file_actions: false
    schemas: {}
  pages:
    path: content
    output: true
    url: /[slug]
    name: Stundet_Home
    description: ''
    icon: wysiwyg
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
      metadata:
      gallery:
    _editables: {}
    _enabled_editors:
      - visual
    _inputs: {}
    _select_data: {}
    _structures: {}
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    schemas: {}
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
source_editor:
  tab_size: 2
  theme: dawn
  show_gutter: false
timezone: Etc/UTC
