paths:
  uploads: public/uploads
  data: data
collections_config: 
  data:
    path: data
    disable_add: true
    disable_add_folder: true
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
sourct_editor:
  tab_size: 4
  show_gutter:  false
  them: 'dawn'
timezone: Etc/UTC
