paths:
  static: public
  uploads: public/uploads
  data: data
collections_config:
  # data:
  #   path: data
  #   output: false
  #   filter:
  #     base:
  #     include:
  #     exclude:
  #   description: ''
  #   icon: notes
  #   _editables: {}
  #   _inputs: {}
  #   _select_data: {}
  #   _structures: {}
  #   disable_add: true
  #   disable_add_folder: true
  #   disable_file_actions: false
  #   schemas: {}
  pages:
    name: Pages
    path: content
    url: '/[slug]'
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
  blog: 
    title: Blog(English)
    path: content/posts
    output: true
    url: '/blog/[slug]'
    icon: article
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: schemas/post.md
  blog_zh_hk:
    title: Blog(Traditional Chinese)
    path: content/posts_zh_hk
    output: true
    url: '/blog/[slug]'
    icon: article
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: schemas/post.md
  blog_fr:
    title: Blog(French)
    path: content/posts_fr
    output: true
    url: '/blog/[slug]'
    icon: article
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: schemas/post.md
  blog_sp:
    title: Blog(Spanish)
    path: content/posts_sp
    output: true
    url: '/blog/[slug]'
    icon: article
    _enabled_editors:
      - content
      - visual
    schemas:
      default:
        path: schemas/post.md
_inputs: 
  avatar:
    type: image
  paragraph:
    type: textarea
  question:
    type: textarea
  answer:
    type: html
  portrait_section[*].description:
    type: html
  testimonials_section.list[*].quote:
    type: textarea
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Blogging
    collections:
      - posts
      - blog
      - blog_zh_hk
      - blog_fr
      - blog_sp
source_editor:
  tab_size: 2
  show_gutter: true
timezone: Etc/UTC
