
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Plans contact Section
  description: Plans contact Section
  icon: "email"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Plans contact Section
  description: 
    en: >-
        Are you a university or institution interested in licensing QuickTakes for
        your students or employees? Email us at ${email}
    zh_hk:
    fr:
    sp:
  buttontxt:
    en: Email Us
    zh_hk:
    fr:
    sp:
  email: info@edkey.com

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.zh_hk:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.fr:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.sp:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea

