
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Experience
  description: About Us Experience
  icon: "work"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Experience section
  contentTitle: 
    en:
    zh_hk:
    fr:
    sp:
  items:
    - image: ./logo/edmodo.svg
    - image: ./logo/redbird.svg
    - image: ./logo/mcgrawhill.svg
    - image: ./logo/netscape.svg
    - image: ./logo/doubleclick.svg
    - image: ./logo/alexa.svg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
