
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: institutions subscription Section
  description: institutions subscription Section
  icon: "email"

# Defines the structure of this component, as well as the default values
blueprint:
  title: institutions subscription 
  contentTitle: Site Licensing & Bulk Subscriptions
  description: We offer institutional licensing on a per seat basis from 25 seats to thousands of seats. Licenses can be set as quarterly, 6-month or the entire school year.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:


