
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: institutions subscription Section
  description: institutions subscription Section
  icon: "email"

# Defines the structure of this component, as well as the default values
blueprint:
  title: institutions subscription 
  contentTitle: 
    en: Site Licensing & Bulk Subscriptions
    zh_hk: 
    fr:
    sp:
  description: 
    en: >-
      <p>We offer institutional licensing on a per seat basis from <strong>25
      seats</strong> to thousands of seats. Licenses can be set as quarterly,
      <strong>6-month</strong> or <strong>the entire school year</strong>.</p>
    zh_hk: 
    fr:
    sp:
  buttonTxt:
    en: Contact Us
    zh_hk: 
    fr: test
    sp:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    type: html
  description.zh_hk:
    type: html
  description.fr:
    type: html
  description.sp:
    type: html

