
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home benefit
  description: Home benefit section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home benefit Section
  items:
      - title: 
          en: Never Forget a Lecture
          zh_hk: 
          fr: 
          sp:  
        description: 
          en: >-
            Record your entire lecture to get back your AI-generated QuickTake!
            Feel confident while you concentrate on listening to your lecture that
            you’ll have the back up you need with AI-developed supercharged study
            notes.
          zh_hk: 
          fr: 
          sp: 
        image: /never-forget-a-lecture.png
        reverse: false
      - title: 
          en: Get Better Grades Now
          zh_hk: 
          fr: 
          sp:  
        description: 
          en: >-
            Upload pre-recorded audio and video files, Youtube URLs and PDFs and
            let your personalized AI sidekick organize all your materials so you
            have an effective way to study for exams and finals.
          zh_hk: 
          fr: 
          sp: 
        image: /get-better-grades-now.png
        reverse: true
      - title:
          en: Chat & Learn with Your Dedicated AI Sidekick, 24/7
          zh_hk: 
          fr: 
          sp:  
        description:
          en: >-
            Need a question answered but can’t get time with your professor? Query
            your AI Sidekick chatbot to discuss topics, get more detailed
            explanations and develop in-depth understanding of all your class
            materials.
          zh_hk: 
          fr: 
          sp:  
        image: /chat-learn-with-ai.png
        reverse: false

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items[*].description.en:
    type: textarea
  items[*].description.zh_hk:
    type: textarea
  items[*].description.fr:
    type: textarea
  items[*].description.sp:
    type: textarea
