
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing contact Section
  description: Pricing contact Section
  icon: "help"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Pricing contact Section
  content: Are you a university or institution interested in licensing QuickTakes for your students or employees? Email us at ${email} 
  buttontxt: Email Us
  email: info@edkey.com

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:


