
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Blog List Section
  description: Blog List Section
  icon: "List"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Blog List Section
  buttonTxt:
    en: View More
    zh_hk:
    fr: 
    sp:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
