version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0
  aws-cli: circleci/aws-cli@2.0.3
  jira-orb: elmtree-askmo/jira-orb@0.0.13

jobs:
  build-staging:
    docker:
      - image: cimg/node:16.20
    environment:
      DOCKER_BUILDKIT: "1"
    steps:
      - checkout
      - jira-orb/slack_start:
          github_organization: elmtree-askmo
          jira_organization: askmo
      - aws-cli/setup
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run:
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
      - run: |
          npx next build
          aws s3 sync ./out s3://staging.quicktakes.io/ --delete
      - run:
          command: aws cloudfront create-invalidation --distribution-id E1GK6MTIKBXLSJ --paths /* && rm -rf build
      - jira-orb/slack_end:
          github_organization: elmtree-askmo
          jira_organization: askmo
      - jira-orb/jira_notify:
          environment_type: staging
          environment: staging  
          job_type: deployment  
          scan_commit_body: true

workflows:
  build-and-push-staging:
    jobs:
      - build-staging:
          context: 
            - askmo_context
            - jira_orb_context
          filters:
            tags:
              only:
                - /^staging-v[\d]{4}[-][\d]{2}[-][\d]{2}[a-z]?$/
            branches:
              ignore: /.*/
