
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Education introduction Section
  description: Education introduction Section
  icon: "description"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Education introduction Section
  contentTitle: 
    en: AI in Education
    zh_hk:
    fr: test
    sp:
  description: 
    en: >-
      The world of AI in education is new and exciting with high potential to
      help students and educators more effectively learn and educate. AI in
      education is also fraught with concerns about how to deploy in meaningful
      ways that include guardrails and best practices. What are the implications
      for the next generation of students and educators? How do we maintain
      checks and balances, or avoid de-skilling? These just some of the
      questions on the mind thought-leaders in the AI edtech space. Check out
      some books and articles below that our staff believes will help educate
      those interested in AI and its promise for education.
    zh_hk:
    fr: test
    sp:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    type: textarea
  description.zh_hk:
    type: textarea
  description.fr:
    type: textarea
  description.sp:
    type: textarea
