
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Benefit
  description: About Us Benefit
  icon: "description"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Benefit section
  list: 
    - title: Mission
      description: Our mission is to help all learners reach their full academic potential through new technologies.
      image: /mission.png
    - title: Vision
      description: We aim to democratize education in ways that allow all students to succeed via personalized learning and AI-enhanced educational tools. 
      image: /vision.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
