
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Benefit
  description: About Us Benefit
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Benefit section
  items: 
    - title: 
        en: Mission
        zh_hk:
        fr: test
        sp:
      description:
        en: >-
          Our mission is to help all learners reach their full academic
          potential through new technologies.
        zh_hk:
        fr: test
        sp:
      image: /mission.png

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items[*].description.en:
    type: textarea
  items[*].description.zh_hk:
    type: textarea
  items[*].description.fr:
    type: textarea
  items[*].description.sp:
    type: textarea
    
