
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: FAQ Section
  description: FAQ Section
  icon: "quiz"

# Defines the structure of this component, as well as the default values
blueprint:
  title: FAQ Section
  contentTitle: 
    en: FAQ
    zh_hk:
    fr:
    sp:
  description: 
    en: >-
      Here are some frequently asked questions about QuickTakes and how it
      works. If these FAQs do not answer your specific question, then we
      recommend sending an email to ${email}
    zh_hk:
    fr:
    sp:
  email: support@edkey.com
  items:
    - question: 
        en: How do I sign up for QuickTakes?
        zh_hk:
        fr: test
        sp:
      answer: 
        en: >-
          <p>You can sign up using the web application on this site or download
          the mobile app from either the Google Play Store or the Apple App
          Store and then sign up when you open the app.</p>
        zh_hk:
        fr: test
        sp:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.zh_hk:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.fr:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  description.sp:
    comment: use ${email} to replace the exact email address in this content and enter the exact email in the email field
    type: textarea
  items[*].question.en:
    type: textarea
  items[*].question.zh_hk:
    type: textarea
  items[*].question.fr:
    type: textarea
  items[*].question.sp:
    type: textarea
  items[*].answer.en:
    type: html
  items[*].answer.zh_hk:
    type: html
  items[*].answer.fr:
    type: html
  items[*].answer.sp:
    type: html
