
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Partnerships
  description: About Us Partnerships
  icon: "description"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Partnerships section
  contentTitle: Partnerships
  description: Interested in working with us? Email us at ${email} for business development and job opportunities.
  buttontxt: Email Us
  email: info@edkey.com

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
