
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Pricing Section
  description: Pricing Section
  icon: "help"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Pricing Section
  list: 
    - label: Free
      itemActiveStyle: false
      minutesLabel: 90 min
      description: weekly recording time
      remark: Reloads weekly
      supportAbility:
        - label: PDF upload
          description: Unlimited at no cost
          activeStyle: false
        - label: Video/Audio file upload
          description: Part of free 90 min
          activeStyle: false
        - label: Youtube URL upload
          description: Part of free 90 min
          activeStyle: false
    - label: Boost
      itemActiveStyle: true
      minutesLabel: 90 min
      description: One time purchase
      remark: Good for 1 month
      supportAbility:
        - label: 90 minutes of free recording time
          description: Reloads weekly
          activeStyle: true
        - label: PDF upload
          description: Unlimited at no cost
          activeStyle: true
        - label: Video/Audio file upload
          description: Part of free 90 min
          activeStyle: true
        - label: Youtube URL upload
          description: Part of free 90 min
          activeStyle: true
    - label: Lite
      itemActiveStyle: true
      minutesLabel: 120 min
      description: weekly recording time
      remark: Reloads weekly
      supportAbility:
        - label: 90 minutes of free recording time
          description: Reloads weekly
          activeStyle: true
        - label: PDF upload
          description: Unlimited at no cost
          activeStyle: true
        - label: Video/Audio file upload
          description: Part of free 90 min
          activeStyle: true
        - label: Youtube URL upload
          description: Part of free 90 min
          activeStyle: true
    - label: Premium
      itemActiveStyle: true
      minutesLabel: 1,110 min
      description: One time purchase
      remark: Good for 1 month
      supportAbility:
        - label: 90 minutes of free recording time
          description: Reloads weekly
          activeStyle: true
        - label: PDF upload
          description: Unlimited at no cost
          activeStyle: true
        - label: Video/Audio file upload
          description: Part of free 90 min
          activeStyle: true
        - label: Youtube URL upload
          description: Part of free 90 min
          activeStyle: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
