
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Schools
  description: Home Schools section
  icon: "campaign"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home Schools Section
  contentTitle: Trusted By Top Students
  content:
      - slide:
        - schoolLogo: /schoolLogo/berkeley.svg
        - schoolLogo: /schoolLogo/colgate.svg
        - schoolLogo: /schoolLogo/penn.svg
        - schoolLogo: /schoolLogo/ucsb.svg
        - schoolLogo: /schoolLogo/stanford.svg
        - schoolLogo: /schoolLogo/columbia.svg
      - slide:
        - schoolLogo: /schoolLogo/cornell.svg
        - schoolLogo: /schoolLogo/rutgers.svg
        - schoolLogo: /schoolLogo/princeton.svg
        - schoolLogo: /schoolLogo/mrgill.svg
        - schoolLogo: /schoolLogo/duke.svg
        - schoolLogo: /schoolLogo/michigan.svg
      - slide:
        - schoolLogo: /schoolLogo/ohio.svg
        - schoolLogo: /schoolLogo/texas.svg
        - schoolLogo: /schoolLogo/toronto.svg
        - schoolLogo: /schoolLogo/colorado.svg
        - schoolLogo: /schoolLogo/wesleyan.svg
        - schoolLogo: /schoolLogo/csu.svg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
