
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Schools
  description: Home Schools section
  icon: "campaign"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home Schools Section
  contentTitle: Schools of Students Using QuickTakes
  content:
      - line: UC Berkeley • Colgate College • University of Pennsylvania • UC Santa Barbara • Stanford University • Cornell University • Rutgers University • Colorado State University • Wesleyan University • Baylor University • Iowa University • Pepperdine University • McGill University • Duke University • University of Michigan • University of Texas
        reverse: false
      - line: University of Arizona • Toronto Metropolitan University • McHenry County College • Salem College • Towson University • California State University • University of Hawaii • Michigan State University • Florida State University • San Mateo County Community College • Princeton University • Presbyterian College
        reverse: true

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
