
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Record
  description: Home Record section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home Record Section
  image: /home-mobile.png
  slogan:
    - item: QuickTakes can help.
    - item: Just hit record!

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
