
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Plans introduction Section
  description: Plans introduction Section
  icon: "description"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Plans introduction Section
  contentTitle: Plans
  description: At QuickTakes, we are committed to keeping cutting-edge technology in education accessible to all, which is why we will always offer a free version of the service to our users. We have multiple subscription options for your convenience whether you rely on QuickTakes everyday or less often.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
