
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Institutions testimonials
  description: Institutions testimonials section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Institutions testimonials section
  contentTitle: QuickTakes Testimonials
  description: Don't just take our word for it. See what students are saying about QuickTakes.
  items:
    - name: Jeremy
      content: This is such a great app. ADHD makes lectures really difficult to get through and retain material, but QuickTakes makes the process a whole lot easier.
      avatar: /insititutions/avatar.svg
    - name: Owen
      content: The extensive functionality blows my mind! This is not work, it's a masterpiece. It even translates on-the-fly too. WOW! 😀 What a bonus for my English-only friends, and my Spanish (ELL) wife too! 
      avatar: /insititutions/avatar2.svg
    - name: Alexis
      content: I started using QuickTakes to record what the teacher was saying, and I must say that this works PERFECTLY.
      avatar: /insititutions/avatar3.svg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  content:
    type: textarea
