
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Institutions testimonials
  description: Institutions testimonials section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Institutions testimonials section
  contentTitle: 
    en: QuickTakes Testimonials
    zh_hk: 
    fr:
    sp:
  description: 
    en: >-
      Don't just take our word for it. See what students are saying about
      QuickTakes.
    zh_hk: 
    fr:
    sp:
  items:
    - name: Jeremy
      content: 
        en: >-
          This is such a great app. ADHD makes lectures really difficult to get
          through and retain material, but QuickTakes makes the process a whole
          lot easier.
        zh_hk: 
        fr:
        sp:
      avatar: /insititutions/avatar.svg

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  description.en:
    type: textarea
  description.zh_hk:
    type: textarea
  description.fr:
    type: textarea
  description.sp:
    type: textarea
  items[*].content.en:
    type: textarea
  items[*].content.zh_hk:
    type: textarea
  items[*].content.fr:
    type: textarea
  items[*].content.sp:
    type: textarea
