
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Banner
  description: Home Banner section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home Banner section
  contentTitle:
      en: "\_Study Smarter, Learn Faster"
      zh-hk:
      fr:
      sp:
    subTitle:
      en: Supercharge learning with your personalized AI study sidekick
      zh-hk:
      fr:
      sp: 
    buttonTxt:
      en: Sign Up Today
      zh-hk:
      fr:
      sp:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
