
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Banner
  description: Home Banner section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home Banner section
  contentTitle: Study Smarter, Learn Faster
  subTitle: Supercharge learning with your personalized AI study sidekick
  buttonTxt: Sign Up Today

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
