
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Founding Team
  description: About Us Founding Team
  icon: "groups"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Founding Team section
  contentTitle: Founding Team
  members: 
    - avatar: /images/photo-Garwin.webp
      name: Garwin Chan
      title: CEO
      description: Garwin Chan is a visionary entrepreneur with a background spanning corporate strategy, private market investing, and cutting-edge technology. As the Co-founder and CEO of Edkey Inc, Garwin spearheads the application of the latest technologies to enhance learning efficacy and foster knowledge sharing. Previously he was the Chief Strategy Officer at Edmodo and its parent company, Netdragon, where he drove country level partnerships among other education innovation initiatives. Garwin was the Chief Financial Officer at The Third Stone Holdings Limited, where he oversaw the parent company of the 5Miles app and held multiple leadership roles at Bain Capital. Garwin received his B.A. and M.B.A. from Harvard Business School.
    - avatar: /images/photo-George.webp
      name: George Chen
      title: President and COO
      description: George Chen has a long history as an Internet company executive.Most recently he was Edmodo’s Chief Business Officer leading Edmodo B2B/B2C online tutoring and managing the country wide rollout to 22+ million students and teachers in Egypt. Prior to Edmodo, George was CMO at 5miles, a start-up mobile marketplace for second-hand products, where he grew the service to more than 15 million users. George was VP of Product Development at Allyes, the largest ad platform and digital marketing agency in China where he was responsible for product management, sales, and operations.  He was the principal engineer at DoubleClick, a subsidiary of Google. George received his masters in Applied Physics from Rice University and BS in Physics from University of Science & Technology of China. In his spare time he plays tennis with his wife and kids and collects wine.
    - avatar: /images/photo-James.webp
      name: James Ku
      title: Sr. Director of Product
      description: An accomplished technology leader with over 25 years of experience in product development, engineering, and operations. Proven expertise in designing and delivering innovative software solutions, leveraging emerging technologies like AI, machine learning, and natural language processing. Co-founded multiple startups in E-Commerce, social media, mobile applications, educational solutions. Adept at leading cross-functional teams, driving product strategy, and optimizing user experiences. Passionate about creating impactful products that solve real-world problems and deliver exceptional value to customers. A visionary thinker with a track record of driving growth and delivering cutting-edge solutions at Oracle and Netscape.
    - avatar: /images/photo-Ale.webp
      name: Alé Di Mare
      title: Head of Engineering
      description: Engineering leader at edtech cos & social learning pioneer
    - avatar: /images/photo-Darian.webp
      name: Darian Patchin
      title: VP Marketing Operations
      description: As a co-founder and VP of Marketing Operations at Edkey, Darian spearheads initiatives to connect students with transformational AI services to help them reach their full academic potential. He focuses on go-to-market strategy, driving user acquisition, engagement as well as product marketing and customer support. Darian's expertise spans the K-12 and higher ed markets, domestically and internationally, focusing on B-to-B and B-to-C services. Darian's career highlights include leadership roles at prominent educational platforms like Edmodo, McGraw-Hill Education and GiftedandTalented.com (originating out of Stanford University), where he orchestrated hyper-growth marketing launches. He’s held leadership positions at seminal Internet consumer start-ups including Alexa Internet, Tribe.com, eTour and Freeloader. Darian's diverse interests include wine, food, soccer, and sci-fi. Darian graduated from Ohio Wesleyan University with a B.A. in History. 

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
