
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us Founding Team
  description: About Us Founding Team
  icon: "groups"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Founding Team section
  contentTitle: Founding Team
  members: 
    - avatar: /images/photo-Garwin.webp
      name: Garwin Chan
      title: CEO
      description: 
        en: >-
          Garwin Chan is an entrepreneur with a background spanning corporate
          strategy, private market investing, and cutting-edge technology. As
          the Co-founder and CEO of Edkey Inc, Garwin spearheads the application
          of the latest technologies to enhance learning efficacy and foster
          knowledge sharing. Previously he was the Chief Strategy Officer at
          Edmodo and its parent company, Netdragon, where he drove country level
          partnerships among other education innovation initiatives. Garwin was
          the Chief Financial Officer at The Third Stone Holdings Limited, where
          he oversaw the parent company of the 5Miles app and held multiple
          leadership roles at Bain Capital. Garwin received his B.A. and M.B.A.
          from Harvard University.
        zh_hk:
        fr: test
        sp:
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  members[*].description.en:
    type: textarea
  members[*].description.zh_hk:
    type: textarea
  members[*].description.fr:
    type: textarea
  members[*].description.sp:
    type: textarea
