
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Plans Section
  description: Plans Section
  icon: "list"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Plans Section
  items: 
    - label: 
        en: Free
        zh_hk:
        fr:
        sp:
      itemActiveStyle: false
      minutesLabel: 
        en: 90 min
        zh_hk:
        fr:
        sp:
      description: 
        en: weekly recording time
        zh_hk:
        fr:
        sp:
      remark: 
        en: Reloads weekly
        zh_hk:
        fr:
        sp:
      supportAbility:
        - label: 
            en: PDF upload
            zh_hk:
            fr:
            sp:
          description: 
            en: Unlimited at no cost
            zh_hk:
            fr:
            sp:
          activeStyle: false
    

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs: