
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home testimonials
  description: Home testimonials section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: Home testimonials Section
  section_title: Testimonials
  list:
    - quote: “This app is super easy to use. It makes learning super intuitive!”
      name: Ken S.
      grade: Sophomore
    - quote: >-
        “This is the app I've been looking for. It's fast, detailed, and
        helping me pass my classes”
      name: Barbara G.
      grade: Freshman
    - quote: “This app is super easy to use. It makes learning super intuitive!”
      name: Tamira B.
      grade: Freshman

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
