
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us About Edkey
  description: About Us About Edkey
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  title: About Edkey section
  About_Edkey:
    - paragraph: Edkey's mission is to help life-long learners reach their full academic potential through new technologies that advance human intelligence through more effective learning & knowledge sharing.

    - paragraph: Our flagship products are QuickTakes and ClassMo. The QuickTakes consumer app (available in the iOS and Android app stores and via web browser) offers college students an easy and effective way to increase their understanding of their course lectures with the help of a personalized AI assistant. The QuickTakes app uses AI to return robust learning materials from class lecture recordings including study guides, outlines, glossaries, practice questions, recommended videos as well as an AI assistant for more in depth studying about the lecture subject matter.

    - paragraph: Edkey Inc. is an educational technology company made of a group of former principal Edmodo executives (over 140m student and teacher users) who collectively have more than 50 years of experience building educational services at institutions including Edmodo, Stanford University, Redbird Advanced Learning, McGraw Hill and technology companies including Netscape, DoubleClick, NetDragon, Alexa and more. EdKey develops technologies, services, and applications focused on the K-12 and Higher Ed educational spaces.

    - paragraph: Founded in fall of 2022 in California, Edkey Inc., has roots in the San Francisco Bay Area. The founding team has a shared belief in personalized, life-long learning and believe that further edtech innovation is needed to democratize access to learning tools that unlock each learner’s full potential.

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
