
# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: About Us
  description: About Us
  icon: "peolple"

# Defines the structure of this component, as well as the default values
blueprint:
  title: About Us section
  contentTitle: 
    en: About Us
    zh_hk:
    fr:
    sp:
  items:
    - paragraph: 
        en:
        zh_hk:
        fr:
        sp:


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  items[*].paragraph.en:
    type: textarea
  items[*].paragraph.zh_hk:
    type: textarea
  items[*].paragraph.fr:
    type: textarea
  items[*].paragraph.sp:
    type: textarea
